site_name: RVIC
site_description: RVIC Streamflow Routing Model
site_author: UW Hydro | Computational Hydrology
copyright: 'Copyright &copy; 2015, <a href="www.hydro.washington.edu/">University of Washington Computational Hydrology Group</a>.'
repo_url: https://github.com/UW-Hydro/RVIC
theme: readthedocs

pages:
- Home: index.md
- About:
  - Model Overview: about/model-overview.md
  - References: about/references.md
- User Guide:
  - User Guide: user-guide/index.md
  - Installing: user-guide/install.md
  - Generating RVIC Parameters: user-guide/parameters.md
  - Running the RVIC Convolution: user-guide/convolution.md
  - Conversion from other VIC Routing Models: user-guide/conversion.md
  - RVIC API: user-guide/api.md
- Model Development:
  - RVIC Development: development/model-development.md
  - Open Source Philosophy: development/open-source.md
- Support:
  - Contact: support/contact.md
  - Frequently Asked Questions: support/faq.md
